name: liteseg
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.03.07
  - certifi=2018.10.15
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.0.2p
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - cycler=0.10.0
  - kiwisolver=1.0.1
  - matplotlib=3.0.2
  - matplotlib-base=3.0.2
  - pyqt=5.6.0
  - sip=4.18.1
  - alabaster=0.7.12
  - asn1crypto=0.24.0
  - astroid=2.0.4
  - babel=2.6.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.0.2
  - bzip2=1.0.6
  - cairo=1.14.12
  - cffi=1.11.5
  - chardet=3.0.4
  - cloudpickle=0.6.1
  - cryptography=2.3.1
  - dbus=1.13.2
  - decorator=4.3.0
  - docutils=0.14
  - entrypoints=0.2.3
  - expat=2.2.6
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gmp=6.1.2
  - graphite2=1.3.12
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.7
  - imagesize=1.1.0
  - intel-openmp=2019.0
  - ipykernel=5.1.0
  - ipython=7.1.1
  - ipython_genutils=0.2.0
  - isort=4.3.4
  - jasper=2.0.14
  - jedi=0.13.1
  - jeepney=0.4
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter_client=5.2.3
  - jupyter_core=4.4.0
  - keyring=16.0.2
  - lazy-object-proxy=1.3.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.35
  - libsodium=1.0.16
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.8
  - markupsafe=1.1.0
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.8.2
  - numpydoc=0.8.0
  - olefile=0.46
  - opencv=3.4.2
  - packaging=18.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pip=18.1
  - pixman=0.34.0
  - prompt_toolkit=2.0.7
  - psutil=5.4.8
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pycodestyle=2.4.0
  - pycparser=2.19
  - pyflakes=2.0.0
  - pygments=2.2.0
  - pylint=2.1.1
  - pyopenssl=18.0.0
  - pyparsing=2.3.0
  - pysocks=1.6.8
  - python=3.7.0
  - python-dateutil=2.7.5
  - pytz=2018.7
  - pyzmq=17.1.2
  - qt=5.6.3
  - qtawesome=0.5.3
  - qtconsole=4.4.2
  - qtpy=1.5.2
  - readline=7.0
  - requests=2.20.1
  - rope=0.11.0
  - setuptools=40.6.2
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sphinx=1.8.2
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - spyder=3.3.1
  - spyder-kernels=0.2.6
  - sqlite=3.25.3
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - urllib3=1.23
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.32.2
  - wrapt=1.10.11
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - pytorch=0.4.1
  - torchvision=0.2.1
  - pip:
    - addict==2.2.0
    - imutils==0.5.1
    - munch==2.3.2
    - pandas==0.23.4
    - protobuf==3.6.1
    - pyyaml==3.13
    - tensorboardx==1.4
    - thop==0.0.22
    - torch==0.4.1.post2
    - torchfile==0.1.0
    - torchsummary==1.5.1
    - tqdm==4.31.1
    - visdom==0.1.8.5
    - websocket-client==0.54.0
    - libgfortran-ng==7.3.0
    - libglu==9.0.0
    - libstdcxx-ng==8.2.0
    - freeglut==3.0.0
    - secretstorage==3.1.0
    - libgcc-ng==8.2.0


prefix: /home/emaraic/anaconda3/envs/pytorch

