name: pytorch
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - mkl_fft=1.0.6=py37h7dd41cf_0
  - mkl_random=1.0.1=py37h4414c95_1
  - numpy=1.15.4=py37h1d66e8a_0
  - numpy-base=1.15.4=py37h81de0dd_0
  - openssl=1.0.2p=h14c3975_0
  - scikit-learn=0.20.0=py37h4989274_1
  - scipy=1.1.0=py37hfa4b5c9_1
  - cycler=0.10.0=py_1
  - kiwisolver=1.0.1=py37h2d50403_2
  - matplotlib=3.0.2=py37h8a2030e_1
  - matplotlib-base=3.0.2=py37h20b835b_1
  - pyqt=5.6.0=py37h8210e8a_7
  - sip=4.18.1=py37hfc679d8_0
  - alabaster=0.7.12=py37_0
  - asn1crypto=0.24.0=py37_0
  - astroid=2.0.4=py37_0
  - babel=2.6.0=py37_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.0.2=py37_0
  - bzip2=1.0.6=h14c3975_5
  - cairo=1.14.12=h8948797_3
  - cffi=1.11.5=py37he75722e_1
  - chardet=3.0.4=py37_1
  - cloudpickle=0.6.1=py37_0
  - cryptography=2.3.1=py37hc365091_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py37_0
  - docutils=0.14=py37_0
  - entrypoints=0.2.3=py37_2
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.12=h23475e2_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py37_0
  - imagesize=1.1.0=py37_0
  - intel-openmp=2019.0=118
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.1.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - isort=4.3.4=py37_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.13.1=py37_0
  - jeepney=0.4=py37_0
  - jinja2=2.10=py37_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py37_0
  - jupyter_client=5.2.3=py37_0
  - jupyter_core=4.4.0=py37_0
  - keyring=16.0.2=py37_0
  - lazy-object-proxy=1.3.1=py37h14c3975_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.35=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markupsafe=1.1.0=py37h7b6447c_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.0=118
  - nbconvert=5.3.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=hf484d3e_0
  - ninja=1.8.2=py37h6bb024c_1
  - numpydoc=0.8.0=py37_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - packaging=18.0=py37_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.1=py37_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=5.3.0=py37h34e0f95_0
  - pip=18.1=py37_0
  - pixman=0.34.0=hceecf20_3
  - prompt_toolkit=2.0.7=py37_0
  - psutil=5.4.8=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycodestyle=2.4.0=py37_0
  - pycparser=2.19=py37_0
  - pyflakes=2.0.0=py37_0
  - pygments=2.2.0=py37_0
  - pylint=2.1.1=py37_0
  - pyopenssl=18.0.0=py37_0
  - pyparsing=2.3.0=py37_0
  - pysocks=1.6.8=py37_0
  - python=3.7.0=h6e4f718_3
  - python-dateutil=2.7.5=py37_0
  - pytz=2018.7=py37_0
  - pyzmq=17.1.2=py37h14c3975_0
  - qt=5.6.3=h39df351_1
  - qtawesome=0.5.3=py37_0
  - qtconsole=4.4.2=py37_0
  - qtpy=1.5.2=py37_0
  - readline=7.0=h7b6447c_5
  - requests=2.20.1=py37_0
  - rope=0.11.0=py37_0
  - secretstorage=3.1.0=py37_0
  - setuptools=40.6.2=py37_0
  - six=1.11.0=py37_1
  - snowballstemmer=1.2.1=py37_0
  - sphinx=1.8.2=py37_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-websupport=1.1.0=py37_1
  - spyder=3.3.1=py37_1
  - spyder-kernels=0.2.6=py37_0
  - sqlite=3.25.3=h7b6447c_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py37h7b6447c_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.23=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.32.2=py37_0
  - wrapt=1.10.11=py37h14c3975_2
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=ha838bed_2
  - pytorch=0.4.1=py37_py36_py35_py27__9.0.176_7.1.2_2
  - torchvision=0.2.1=py37_1
  - pip:
    - addict==2.2.0
    - brambox==1.1.0
    - imutils==0.5.1
    - pandas==0.23.4
    - protobuf==3.6.1
    - pyyaml==3.13
    - tensorboardx==1.4
    - thop==0.0.22
    - torch==0.4.1.post2
    - torchfile==0.1.0
    - torchsummary==1.5.1
    - visdom==0.1.8.5
    - websocket-client==0.54.0
prefix: /home/emaraic/anaconda3/envs/pytorch

